name: ML Pipeline Automation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint black bandit isort pytest

      - name: Format code with Black
        run: |
          source venv/bin/activate
          black . --line-length 120
      - name: Commit formatting changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Auto-format code with Black" || echo "No changes to commit"
          git push || echo "No push needed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sort imports with isort
        run: |
          source venv/bin/activate
          isort --check-only --diff . || true
      - name: Lint with Pylint
        run: |
          source venv/bin/activate
          pylint *.py --max-line-length=120 --disable=C0301 || true
      - name: Check security with Bandit
        run: |
          source venv/bin/activate
          bandit -r . -ll || true

      - name: Run full pipeline
        run: |
          source venv/bin/activate
          python main.py all
        env:
          MLFLOW_TRACKING_URI: sqlite:///mlflow.db

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/ -v || true

      - name: Upload MLflow artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            *.png
            *.csv
            model.joblib
          retention-days: 7

      - name: Upload MLflow database
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-db
          path: mlflow.db
          retention-days: 7
